import fileinput

input = open(r'G:\Coding\D3\data\china-provinces_old.json', 'r', encoding="utf-8")
output = open(r'G:\Coding\D3\data\china-provinces.json', 'w', encoding="utf-8")

content = input.read()

content = content.replace('上海|上海', '上海')
content = content.replace('內蒙古自治區|内蒙古自治区', '内蒙古')
content = content.replace('北京|北京', '北京')
content = content.replace('吉林', '吉林')
content = content.replace('四川', '四川')
content = content.replace('天津|天津', '天津')
content = content.replace('安徽|安徽', '安徽')
content = content.replace('寧夏回族自治區|宁夏回族自治区', '宁夏')
content = content.replace('山東|山东', '山东')
content = content.replace('山西', '山西')
content = content.replace('廣東|广东', '广东')
content = content.replace('廣西壯族自治區|广西壮族自治区', '广西')
content = content.replace('新疆維吾爾自治區|新疆维吾尔自治区', '新疆')
content = content.replace('江蘇|江苏', '江苏')
content = content.replace('江西', '江西')
content = content.replace('河北', '河北')
content = content.replace('河南', '河南')
content = content.replace('浙江', '浙江')
content = content.replace('海南', '海南')
content = content.replace('湖北', '湖北')
content = content.replace('湖南', '湖南')
content = content.replace('甘肅|甘肃', '甘肃')
content = content.replace('福建', '福建')
content = content.replace('西藏自治區|西藏自治区', '西藏')
content = content.replace('貴州|贵州', '贵州')
content = content.replace('遼寧|辽宁', '辽宁')
content = content.replace('重慶|重庆', '重庆')
content = content.replace('陝西|陕西', '陕西')
content = content.replace('雲南|云南', '云南')
content = content.replace('青海', '青海')
content = content.replace('黑龙江省|黑龍江省', '黑龙江')

output.write(content)
